# Generated by Django 4.2.1 on 2023-05-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name_plural': 'Promoções'},
        ),
    ]
