# Generated by Django 4.1.7 on 2023-05-30 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_promocao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_lista_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listacompras', verbose_name='ListaCompras'),
        ),
    ]
