# Generated by Django 4.1.7 on 2023-05-31 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_id_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_endereco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.endereco', verbose_name='Endereço'),
        ),
    ]
