# Generated by Django 4.1.7 on 2023-05-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_id_endereco_usuario_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereço'},
        ),
        migrations.AlterModelOptions(
            name='listacompras',
            options={'verbose_name_plural': 'lista compras'},
        ),
        migrations.AlterModelOptions(
            name='mercado',
            options={'verbose_name_plural': 'Mercado'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuario'},
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='id_mercado',
            new_name='mercado',
        ),
        migrations.RemoveField(
            model_name='mercado',
            name='id_endereco',
        ),
        migrations.AddField(
            model_name='mercado',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.endereco', verbose_name='Endereço'),
        ),
    ]
