# Generated by Django 4.1.7 on 2023-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_endereco_options_alter_listacompras_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='categoria',
            field=models.CharField(blank=True, choices=[('padaria', 'Padaria'), ('hortifruti', 'Hortifruti'), ('acougue', 'Açougue'), ('bebidas', 'Bebidas')], max_length=100, null=True, verbose_name='Categoria'),
        ),
    ]
