# Generated by Django 4.1.7 on 2023-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_promocao_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img_promocoes', verbose_name='ImagemPromoção'),
        ),
    ]
