# Generated by Django 4.1.7 on 2023-06-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_promocao_informacao_adicional_promocao_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autenticacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
